// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExistsKey(arg1) {
  return window['go']['main']['App']['ExistsKey'](arg1);
}

export function GetKey(arg1) {
  return window['go']['main']['App']['GetKey'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTTL(arg1) {
  return window['go']['main']['App']['GetTTL'](arg1);
}

export function SetKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKey'](arg1, arg2, arg3);
}

export function TriggerSnapshot() {
  return window['go']['main']['App']['TriggerSnapshot']();
}
