// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:number):Promise<main.Result>;

export function DeleteKey(arg1:string):Promise<main.Result>;

export function Disconnect():Promise<main.Result>;

export function ExistsKey(arg1:string):Promise<main.Result>;

export function GetKey(arg1:string):Promise<main.Result>;

export function GetStats():Promise<main.Result>;

export function GetTTL(arg1:string):Promise<main.Result>;

export function SetKey(arg1:string,arg2:string,arg3:number):Promise<main.Result>;

export function TriggerSnapshot():Promise<main.Result>;
